### ISSUE TITLE
ASM make hydrate failed

### ISSUE THREAD

**Issue by kindomLee** [GoogleCloudPlatform/kubeflow-distribution#389]
asm make file will use `asmcli-precheck` during the hydrate, where the `bash` built in commands `pushd`, `popd` are used.
This will make the runtime error because of the program  default`/bin/sh' is used as the shell.

```bash
asmcli: -------------
asmcli: Successfully validated all requirements to install ASM.
pushd upstream && ./istioctl experimental precheck && popd
/bin/sh: 1: pushd: Permission denied
make[1]: *** [Makefile:75: asmcli-precheck] Error 127
```

**Comment by gkcalat** [comment]
Hi @kindomLee!
Thank you for reporting. This issue has been fixed in v1.6.1 release.
