### ISSUE TITLE
Upgrade MySQL to 8.0

### ISSUE THREAD

**Issue by gkcalat** [GoogleCloudPlatform/kubeflow-distribution#391]
As MySQL 8 is a default version in GCP and katib, it was proposed to upgrade MySQL version to 8.0.

        cc @gkcalat for upgrading MySQL version in the future release.

_Originally posted by @zijianjoy in https://github.com/kubeflow/gcp-blueprints/issues/382#issuecomment-1255648227_
     
Additional docs:
* [MySQL 8.0 release notes](https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html)
* [Instruction on upgrading SQL](https://cloud.google.com/sql/docs/mysql/upgrade-major-db-version-inplace#plan_a_major_version_upgrade)
* [GCP MySQL versions](https://cloud.google.com/sql/docs/mysql/db-versions)
* [GCP supported machine types](https://cloud.google.com/sql/docs/mysql/create-instance#machine-types)
* [GCP DB settings](https://cloud.google.com/sql/docs/mysql/flags#rest-v1)

Consideration:
* [ ] Is it a breaking change for users using KF 1.6.0 and prior?
* [ ] Do we need to upgrade tier?
* [ ] Do we need to enforce `utf8` charset as MySQL8 migrated to `utf8mb4`?

**Comment by zijianjoy** [comment]
FYI, MLMD and Argo have already migrated to MySQL 8. And KFP on AI Platform Pipelines also allows us to configure MySQL 8 connection too. That means that the usability on MySQL 8 should be verified already. However, we need to do the followings:

1. Upgrade KFP base mysql deployment to v8: https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml#L29
2. Validate the upgrade from v5 to v8 in full Kubeflow mode so we can determine whether it is a breaking change.
3. I think there should still be some degree of breaking changes any way, so we need to update documentation about it.
