### ISSUE TITLE
Creation of node pools using node images based on Docker container runtimes is not supported in GKE

### ISSUE THREAD

**Issue by itsazzad** [GoogleCloudPlatform/kubeflow-distribution#416]
management❯ `make apply-cluster`                                                                                                          
kubeflow-distribution/git/master !

```
The management cluster name "kubeflow-mgmt" is valid.
# Delete the directory so any resources that have been removed
# from the manifests will be pruned
rm -rf manifests/build/cluster
mkdir -p manifests/build/cluster
kustomize build /home/sazzad/kubeflow-distribution/management/manifests/cluster -o manifests/build/cluster
# Create the cluster
anthoscli apply -f manifests/build/cluster
I0321 11:14:58.031970    1807 main.go:234] reconcile serviceusage.cnrm.cloud.google.com/Service container.googleapis.com
I0321 11:15:02.178266    1807 main.go:234] reconcile container.cnrm.cloud.google.com/ContainerCluster kubeflow-mgmt
Unexpected error: error reconciling objects: error reconciling ContainerCluster:kubeflow-380816/kubeflow-mgmt: error creating GKE cluster kubeflow-mgmt: googleapi: Error 400:
        (1) Creation of node pools using node images based on Docker container runtimes is not supported in GKE v1.23. This is to prepare for the removal of Dockershim in Kubernetes v1.24. We recommend that you migrate to image types based on Containerd (examples). For more information, contact Cloud Support
        (2) Creation of node pools using node images based on Docker container runtimes is not supported in GKE v1.24+ clusters as Dockershim has been removed in Kubernetes v1.24.
make: *** [Makefile:75: apply-cluster] Error 1
```

**Comment by gkcalat** [comment]
Hi @itsazzad!

Have you changed the runtime to Docker?

I just verified deployment of both management and kubeflow clusters using the latest tag `v1.7.0-rc.0` (same as the `master` branch as of March 24, 2023). Can you try using this tag?

**Comment by itsazzad** [comment]
Hi @gkcalat,
I have not changed anything except in the `env.sh`.
management part was working with 1.6 but not Kubeflow.
Kubeflow worked with the master version but management threw that docker error.

**Comment by gkcalat** [comment]
Hi @itsazzad,

FYI, you only need a single `management` cluster per multiple `kubeflow` clusters. Even if they are in different projects.

As I understood (correct me if I am wrong), I have deployed the `management` cluster and you are looking for help deploying the `kubeflow` cluster. If so, then do the following (skip steps that you have already completed):

1. Make sure to [set up the GCP project](https://googlecloudplatform.github.io/kubeflow-gke-docs/docs/deploy/project-setup/). Most like you will need to authenticate (needs a web-browser) and enable necessary APIs:
```bash
gcloud auth login     # login and authorize gcloud

gcloud services enable \
  serviceusage.googleapis.com \
  compute.googleapis.com \
  container.googleapis.com \
  iam.googleapis.com \
  servicemanagement.googleapis.com \
  cloudresourcemanager.googleapis.com \
  ml.googleapis.com \
  iap.googleapis.com \
  sqladmin.googleapis.com \
  meshconfig.googleapis.com \
  krmapihosting.googleapis.com \
  servicecontrol.googleapis.com \
  endpoints.googleapis.com \
  cloudbuild.googleapis.com
```
2. Copy source to a new folder and checkout `v1.7.0-rc.0` tag:
```bash
mkdir temp && cd temp
git https://github.com/GoogleCloudPlatform/kubeflow-distribution.git && cd kubeflow-distribution/kubeflow`
git checkout v1.7.0-rc.0
```

3. Edit `env.sh` using your text editor (e.g. `vim env.sh` or `nano env.sh`). I recommend to set the new kubeflow cluster name - `KF_NAME`.
4. Check your `CLIENT_ID` and `CLIENT_SECRET` (see [instructions](https://googlecloudplatform.github.io/kubeflow-gke-docs/docs/deploy/oauth-setup/)), your `management` cluster's project (it might be the same as `KF_PROJECT`) and set environment variables:
```bash
source env.sh

export CLIENT_ID=<Your CLIENT_ID>
export CLIENT_SECRET=<Your CLIENT_SECRET>
export MGMT_PROJECT=<the project where you deploy your management cluster>
```
5. Pull and configure the manifests and deploy `kubeflow` cluster:
```bash
bash ./pull-upstream.sh && bash kpt-set.sh && make apply-kcc && make apply
```
6. Wait until you get your deployement ready:
```bash
kubectl -n kubeflow get all
```
7. Add viewer role to your account to access the dashboard (replace `<EMAIL>`):
```bash
gcloud projects add-iam-policy-binding "${KF_PROJECT}" --member=user:<EMAIL> --role=roles/iap.httpsResourceAccessor
```
8. Access the dashboard (it may take time to for DNS records to propagate and set up an SSL certificate) using the ingress URL:
```bash
echo $(kubectl -n istio-system get ingress envoy-ingress -o=jsonpath={.spec.rules[0].host})
```

Try the steps above and provide more information for troubleshooting if you encounter an issue (e.g. complete output from terminal window, order of the steps you completed and values of the variables you set. Note: **be aware that this is a public discussion**).

**Comment by gkcalat** [comment]
Kubeflow on Google Cloud v1.7.0 [has been released](https://github.com/GoogleCloudPlatform/kubeflow-distribution/releases/tag/v1.7.0). Please, upgrade your deployment.
