### ISSUE TITLE
kubeflow.org_profiles.yaml causes errors with creationTimestamp line

### ISSUE THREAD

**Issue by bconsolvo** [GoogleCloudPlatform/kubeflow-distribution#431]
Whenever this file is generated:

~/kubeflow-distribution/kubeflow/apps/profiles/upstream/crd/bases/kubeflow.org_profiles.yaml

The line that needs to be removed is:
```bash
creationTimestamp: null
```

You have to keep removing this every time you do the `pull-upstream.sh` script. 

Please fix, thanks!

Also brought up here:
https://github.com/kubeflow/kubeflow/issues/7041#issuecomment-1493434289

**Comment by Linchin** [comment]
temporarily fixed by https://github.com/kubeflow/kubeflow/pull/7279
