### ISSUE TITLE
when running kubeflow pipeline it spins up different shape of machine than what is in my cluster

### ISSUE THREAD

**Issue by bconsolvo** [GoogleCloudPlatform/kubeflow-distribution#436]
I have Kubeflow up and running on GCP. But my problem is that when I ask it to run my Kubeflow Pipeline that I upload (as a YAML file), it decides to pick and spin up brand new E2 instances rather than using the C3 machine shape instances that I have running in my Kubeflow cluster. Not sure why it won't automatically go and just use the C3 machine shapes I already have running. I can post the pipeline, but it is quite long and didn't want to be too verbose here.

**Comment by Linchin** [comment]
Thank you for bringing this up. This should be a node selector feature in Kubeflow Pipelines, which it now supports via platform-specific features. See documentation here for how to implement node selector:
https://kfp-kubernetes.readthedocs.io/en/kfp-kubernetes-1.0.0/source/kubernetes.html

If you have trouble selecting node when running pipelines, please open an issue at the [Kubeflow Pipelines repo](https://github.com/kubeflow/pipelines).
